nodeLinker: hoisted

registries:
  https://europe-west8-npm.pkg.dev/open-gto-2/goat/:
    scopes:
      - '@goatjs'

fetchRetries: 0

fetchTimeout: 900000

packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@goatjs/*'

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  lefthook: true
  unrs-resolver: true
