/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

import type {
  BadRequestError,
  EffectHttpApiErrorBadRequest,
  InvalidCursorError,
  InvalidRequestError,
  NotFoundError,
  QuestionNotFoundError,
  SessionBusyError,
  UnauthorizedError,
} from '@opencode-ai/sdk/v2/types';

export type OpencodeError =
  | EffectHttpApiErrorBadRequest
  | InvalidRequestError
  | NotFoundError
  | BadRequestError
  | UnauthorizedError
  | SessionBusyError
  | QuestionNotFoundError
  | InvalidCursorError;

const OPENCODE_TAGS = new Set([
  'BadRequest',
  'InvalidRequestError',
  'UnauthorizedError',
  'SessionBusyError',
  'QuestionNotFoundError',
  'InvalidCursorError',
]);
const OPENCODE_NAMES = new Set(['BadRequest', 'NotFoundError']);

export const isOpencodeError = (err: unknown): err is OpencodeError => {
  if (typeof err !== 'object' || err === null) return false;
  if ('_tag' in err && typeof err._tag === 'string') return OPENCODE_TAGS.has(err._tag);
  if ('name' in err && typeof err.name === 'string') return OPENCODE_NAMES.has(err.name);
  return false;
};

export const opencodeError = (err: OpencodeError): Error => new Error(getOpencodeErrorMessage(err), { cause: err });

export const getOpencodeErrorMessage = (err: OpencodeError): string => ('name' in err ? err.data.message : getRequestErrorMessage(err));

const getRequestErrorMessage = (
  err: EffectHttpApiErrorBadRequest | InvalidRequestError | UnauthorizedError | SessionBusyError | QuestionNotFoundError | InvalidCursorError,
): string => {
  switch (err._tag) {
    case 'BadRequest': {
      return 'Bad request';
    }
    case 'InvalidRequestError':
    case 'UnauthorizedError':
    case 'SessionBusyError':
    case 'QuestionNotFoundError':
    case 'InvalidCursorError': {
      return err.message;
    }
  }
};
