/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

import { capitalize } from '../../core/capitalize.ts';

export const getProjectName = (worktree: string): string => {
  const sep = worktree.includes('/') ? '/' : '\\';
  if (worktree === '/') return 'Root';
  const name = worktree.split(sep).at(-1) ?? '';
  return name.split(/[-_]/).map(capitalize).join(' ');
};
