/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

/* eslint-disable no-console */

const reset = '\u001B[0m';

const colors = {
  gray: '\u001B[90m',
  cyan: '\u001B[36m',
  yellow: '\u001B[33m',
  red: '\u001B[31m',
  green: '\u001B[32m',
} as const;

const colorize = (color: keyof typeof colors, text: string): string => `${colors[color]}${text}${reset}`;

export type LogLevel = 'none' | 'info' | 'debug';

interface Logger {
  debug: (scope: string, message: string) => void;
  info: (scope: string, message: string) => void;
  warn: (scope: string, message: string) => void;
  error: (scope: string, message: string, err?: unknown) => void;
  init: (options: { logLevel: LogLevel }) => void;
}

let currentLevel: LogLevel = 'none';
let initialized = false;

const formatScope = (scope: string): string => colorize('gray', `[${scope}]`);

const warnUninitialized = (method: string): void => {
  if (!initialized) {
    console.warn(`${colorize('yellow', 'warn')} ${formatScope('logger')} logger.${method}() called before logger.init() -- logs may be suppressed`);
  }
};

export const logger = {
  init: ({ logLevel }: { logLevel: LogLevel }): void => {
    currentLevel = logLevel;
    initialized = true;
  },
  debug: (scope: string, message: string): void => {
    warnUninitialized('debug');
    if (currentLevel !== 'debug') return;
    console.log(`${colorize('cyan', 'debug')} ${formatScope(scope)} ${message}`);
  },
  info: (scope: string, message: string): void => {
    warnUninitialized('info');
    if (currentLevel === 'none') return;
    console.log(`${colorize('green', 'info')} ${formatScope(scope)} ${message}`);
  },
  warn: (scope: string, message: string): void => {
    warnUninitialized('warn');
    if (currentLevel === 'none') return;
    console.warn(`${colorize('yellow', 'warn')} ${formatScope(scope)} ${message}`);
  },
  error: (scope: string, message: string, err?: unknown): void => {
    warnUninitialized('error');
    if (currentLevel === 'none') return;
    console.error(`${colorize('red', 'error')} ${formatScope(scope)} ${message}`, err ?? '');
  },
} satisfies Logger;
