/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

export const isErrorWithCode = (err: unknown): err is Error & { code: string } => {
  return err instanceof Error && 'code' in err && typeof err.code === 'string';
};
