/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

export type FetchErrorStatus = number | 'fetch failed';

class FetchError extends Error {
  status: FetchErrorStatus;
  url: string;

  constructor(message: string, status: FetchErrorStatus, url: string) {
    super(message);
    this.status = status;
    this.name = 'FetchError';
    this.url = url;
    Object.setPrototypeOf(this, FetchError.prototype);
  }
}

export const fetchError = (message: string, { status, url }: { status: FetchErrorStatus; url: string }) => {
  return new FetchError(message, status, url);
};

export const isFetchError = (err: unknown) => {
  return err instanceof FetchError;
};

export type { FetchError };
