/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

// eslint-disable-next-line goatjs/no-array-includes
export const includes = <T>(source: readonly T[], item: unknown): item is T => (source as readonly unknown[]).includes(item);

export const arrayMove = (arr: unknown[], fromIndex: number, toIndex: number) => {
  const el = arr.splice(fromIndex, 1);
  arr.splice(toIndex, 0, ...el);
};

export const getUniqueArrayByKey = <T extends Record<K, string>, K extends keyof T>(arr: T[], key: K): T[] => {
  return new Map(arr.map((item) => [item[key], item])).values().toArray();
};

export const shuffleArray = (array: unknown[]) => {
  for (let i = array.length - 1; i > 0; i--) {
    // eslint-disable-next-line sonarjs/pseudo-random
    const j = Math.floor(Math.random() * (i + 1));
    const temp = array[i];
    const val = array.at(j);
    array[i] = val;
    array[j] = temp;
  }
};

export const getDuplicates = <T>(array: T[]) => array.filter((e, i, a) => a.indexOf(e) !== i);

export const indexOf = (source: unknown[], searchElement: unknown, fromIndex?: number) => {
  // eslint-disable-next-line sonarjs/argument-type
  const value = source.indexOf(searchElement, fromIndex);
  if (value === -1) throw new Error('Index not found');
  return value;
};

export const lastIndexOf = (source: unknown[], searchElement: unknown, fromIndex?: number) => {
  // eslint-disable-next-line sonarjs/argument-type
  const value = source.lastIndexOf(searchElement, fromIndex);
  if (value === -1) throw new Error('Index not found');
  return value;
};
