/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

export const capitalize = (string: string) => {
  const firstLetter = string.at(0);
  if (!firstLetter) return string;
  return firstLetter.toUpperCase() + string.slice(1);
};
