/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

/* eslint-disable @typescript-eslint/no-unsafe-type-assertion */
/** Use this instead of Object.entries to get typed entries. */
export const getEntries = <T extends object>(obj: T) => {
  return Object.entries(obj) as [keyof T, T[keyof T]][];
};

/** Use this instead of Object.keys to get typed keys. */
export const getKeys = <T extends object>(obj: T) => {
  return Object.keys(obj) as (keyof T)[];
};

/** Use this instead of Object.values to get typed values. */
export const getValues = <T extends object>(obj: T) => {
  return Object.values(obj) as T[keyof T][];
};

/** a more elegant and inline way of spreading rest object. This create a new object and don't modify the existing one. */
export const omit = <T extends object, K extends keyof T>(object: T, fields: K[]): Omit<T, K> => {
  const fieldSet = new Set(fields);
  return Object.fromEntries(Object.entries(object).filter(([key]) => !fieldSet.has(key as K))) as Omit<T, K>;
};
