/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

export interface Success<T> {
  data: T;
  error?: undefined;
}

export interface Failure<E> {
  data?: undefined;
  error: E;
}

type Result<T, E = unknown> = Success<T> | Failure<E>;

// Main wrapper function
export const safeTryCatch = async <T, E = unknown>(promise: Promise<T>): Promise<Result<T, E>> => {
  try {
    const data = await promise;
    return { data };
  } catch (error) {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
    return { error: error as E };
  }
};
