/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

class ValidationError extends Error {
  data: unknown;
  constructor(message: string, data: unknown) {
    super(message);
    this.name = 'ValidationError';
    this.data = data;
    Object.setPrototypeOf(this, ValidationError.prototype);
  }
}

export const validationError = (message: string, { data }: { data: unknown }) => new ValidationError(message, data);
export const isValidationError = (err: unknown) => err instanceof ValidationError;
export type { ValidationError };
