/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

import { includes } from '../core/array.ts';

const knownStatuses = [400, 401, 403, 404, 409, 410, 416, 418, 422, 429, 451, 500, 501, 502, 503, 504] as const;

export type ServerErrorStatus = (typeof knownStatuses)[number];

export interface ServerErrorParams<S extends ServerErrorStatus = ServerErrorStatus> {
  readonly status: S;
  readonly cause?: unknown;
}

export class ServerError<S extends ServerErrorStatus = ServerErrorStatus> extends Error {
  readonly status: S;
  readonly log: boolean;

  constructor(message: string, status: S, { cause, log = true }: { cause?: unknown; log?: boolean } = {}) {
    super(message);
    this.status = status;
    this.cause = cause;
    this.log = log;
    this.name = 'ServerError';
    Object.setPrototypeOf(this, ServerError.prototype);
  }
}

type PreErrorParams = Omit<ServerErrorParams, 'status'> & { log?: boolean; message?: string };

export const isServerError = (err: unknown): err is ServerError => err instanceof ServerError;

export const serverError = <S extends ServerErrorStatus>(message: string, p: ServerErrorParams<S> & { log?: boolean }) => {
  return new ServerError(message, p.status, p);
};

export const fromHttpStatus = (status: number): ServerErrorStatus => {
  if (includes(knownStatuses, status)) return status;
  if (status >= 400 && status < 500) return 400;
  return 500;
};

// 4xx client errors
export const badRequest = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Bad Request', 400 as const, p);
export const unauthorized = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Unauthorized', 401 as const, p);
export const forbidden = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Forbidden', 403 as const, p);
export const notFound = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Not Found', 404 as const, p);
export const conflict = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Conflict', 409 as const, p);
export const gone = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Gone', 410 as const, p);
export const unprocessableEntity = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Unprocessable Entity', 422 as const, p);
export const tooManyRequests = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Too Many Requests', 429 as const, p);
export const imATeapot = (p?: PreErrorParams) => new ServerError(p?.message ?? "I'm a Teapot", 418 as const, p);
export const unavailableForLegalReasons = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Unavailable For Legal Reasons', 451 as const, p);

// 5xx server errors
export const internalServerError = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Internal Server Error', 500 as const, p);
export const notImplemented = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Not Implemented', 501 as const, p);
export const badGateway = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Bad Gateway', 502 as const, p);
export const serviceUnavailable = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Service Unavailable', 503 as const, p);
export const gatewayTimeout = (p?: PreErrorParams) => new ServerError(p?.message ?? 'Gateway Timeout', 504 as const, p);
