/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

import * as z from 'zod/v4/core';
import fs from 'node:fs/promises';
import path from 'node:path';
import { isErrorWithCode } from '../core/errors/code.ts';
import { parseError } from '../core/error.ts';

export type StoreError =
  { type: 'validation'; message: string; data: unknown } | { type: 'fs'; message: string } | { type: 'json'; message: string; raw: string };

export type StoreOpResult<T> = { data: T; error?: undefined } | { data?: undefined; error: StoreError };

export interface StoreParams<T extends z.$ZodType> {
  directory: string;
  initial?: z.infer<T>;
  persist?: boolean;
}

export interface StoreResult<T extends z.$ZodType, TParams extends StoreParams<T>> {
  get: TParams['initial'] extends z.infer<T> ? () => Promise<StoreOpResult<z.infer<T>>> : () => Promise<StoreOpResult<z.infer<T> | undefined>>;
  set: (
    value: z.infer<T> | ((prev: TParams['initial'] extends z.infer<T> ? z.infer<T> : z.infer<T> | undefined) => z.infer<T> | Promise<z.infer<T>>),
  ) => Promise<StoreOpResult<z.infer<T>>>;
  clear: () => Promise<void>;
}

export const createStore2 = <T extends z.$ZodType, TParams extends StoreParams<T>>(
  name: string,
  schema: T,
  { directory, initial, persist = true }: TParams,
): StoreResult<T, TParams> => {
  let isInitialized = false;
  type StoreType = z.infer<T>;
  const configFile = path.join(directory, `${name}.json`);

  const getBuffer = async () => {
    try {
      const data = await fs.readFile(configFile);
      return { data };
    } catch (err) {
      if (isErrorWithCode(err) && err.code === 'ENOENT') return { data: undefined };
      return { error: { type: 'fs' as const, message: parseError(err).message } };
    }
  };

  const initialize = async () => {
    if (persist) {
      try {
        await fs.mkdir(directory, { recursive: true });
      } catch (err) {
        return { error: { type: 'fs' as const, message: parseError(err).message } };
      }

      const { data, error } = await getBuffer();
      if (error) return { error };
      if (data) {
        const result = await z.safeParseAsync(schema, JSON.parse(data.toString()));
        if (!result.success) return { error: { type: 'validation' as const, message: result.error.message, data: result.data } };
      }
    }

    return { data: true };
  };

  let currentConfig: StoreType | undefined;

  const get = async (): Promise<StoreOpResult<StoreType | undefined>> => {
    if (!isInitialized) {
      const { data, error } = await initialize();
      if (error) return { error };
      isInitialized = data;
    }
    if (persist && currentConfig === undefined) {
      const bufferData = await getBuffer();
      if (bufferData.error) return { error: bufferData.error };
      if (!bufferData.data) return { data: undefined };
      const raw = bufferData.data.toString();
      try {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
        currentConfig = JSON.parse(raw) as StoreType;
      } catch (err) {
        return { error: { type: 'json' as const, message: parseError(err).message, raw } };
      }
    }

    return { data: currentConfig ?? initial };
  };

  const write = async (value: StoreType): Promise<StoreOpResult<StoreType>> => {
    const result = await z.safeParseAsync(schema, value);
    if (!result.success) {
      return { error: { type: 'validation' as const, message: result.error.message, data: value } };
    }

    currentConfig = result.data;
    if (persist) await fs.writeFile(configFile, JSON.stringify(currentConfig));
    return { data: currentConfig };
  };

  const isUpdater = (
    v: StoreType | ((prev: StoreType | undefined) => StoreType | Promise<StoreType>),
  ): v is (prev: StoreType | undefined) => StoreType | Promise<StoreType> => typeof v === 'function';

  // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
  return {
    get,
    set: async (value: StoreType | ((prev: StoreType | undefined) => StoreType | Promise<StoreType>)) => {
      let resolved;
      if (isUpdater(value)) {
        // if set is called before get, we have to call get ourself otherwise currentConfig is not set
        if (currentConfig === undefined) {
          await get();
        }
        resolved = await value(currentConfig ?? initial);
      } else {
        resolved = value;
      }
      return write(resolved);
    },
    clear: async () => {
      if (initial === undefined) {
        if (persist) {
          try {
            await fs.rm(configFile);
          } catch {}
        }
        currentConfig = undefined;
      } else {
        await write(initial);
      }
    },
  } as StoreResult<T, TParams>;
};
