/**
 * This file was automatically generated by @goatjs/core
 * Do not modify it manually
 */

import * as z from 'zod/v4/core';
import fs from 'node:fs/promises';
import path from 'node:path';
import { isErrorWithCode } from '../core/errors/code.ts';
import { parseAsync } from '../zod/parse.ts';

export type StoreErrorDirective = 'warn' | 'error' | 'delete';

export interface StoreParams<T extends z.$ZodType> {
  directory: string;
  initial?: z.infer<T>;
  persist?: boolean;
  onCorrupted?: StoreErrorDirective;
}

export interface StoreResult<T extends z.$ZodType, TParams extends StoreParams<T>> {
  get: TParams['initial'] extends z.infer<T> ? () => Promise<z.infer<T>> : () => Promise<z.infer<T> | undefined>;
  set: (
    value: z.infer<T> | ((prev: TParams['initial'] extends z.infer<T> ? z.infer<T> : z.infer<T> | undefined) => z.infer<T> | Promise<z.infer<T>>),
  ) => Promise<z.infer<T>>;
  clear: () => Promise<void>;
}

export const createStore = async <T extends z.$ZodType, TParams extends StoreParams<T>>(
  name: string,
  schema: T,
  { directory, initial, persist = true, onCorrupted = 'error' }: TParams,
): Promise<StoreResult<T, TParams>> => {
  if (persist) await fs.mkdir(directory, { recursive: true });
  type StoreType = z.infer<T>;
  const configFile = path.join(directory, `${name}.json`);

  const getBuffer = async () => {
    try {
      return await fs.readFile(configFile);
    } catch (err) {
      if (isErrorWithCode(err) && err.code === 'ENOENT') return;
      throw err;
    }
  };

  // validate prev stored
  if (persist) {
    const buf = await getBuffer();
    if (buf) {
      const result = await z.safeParseAsync(schema, JSON.parse(buf.toString()));
      if (!result.success) await handleCorrupted(onCorrupted, name, configFile);
    }
  }
  //

  let currentConfig: StoreType | undefined;

  const get = async () => {
    if (persist && currentConfig === undefined) {
      const buf = await getBuffer();
      if (buf) {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
        currentConfig = JSON.parse(buf.toString()) as StoreType;
      }
    }

    return currentConfig ?? initial;
  };

  const write = async (value: StoreType) => {
    currentConfig = await parseAsync(schema, value);
    if (persist) await fs.writeFile(configFile, JSON.stringify(currentConfig));
  };

  const isUpdater = (
    v: StoreType | ((prev: StoreType | undefined) => StoreType | Promise<StoreType>),
  ): v is (prev: StoreType | undefined) => StoreType | Promise<StoreType> => typeof v === 'function';

  // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
  return {
    get,
    set: async (value: StoreType | ((prev: StoreType | undefined) => StoreType | Promise<StoreType>)) => {
      let resolved;
      if (isUpdater(value)) {
        // if set is called before get, we have to call get ourself otherwise currentConfig is not set
        if (currentConfig === undefined) {
          await get();
        }
        resolved = await value(currentConfig ?? initial);
      } else {
        resolved = value;
      }
      await write(resolved);
      return currentConfig;
    },
    clear: async () => {
      if (initial === undefined) {
        if (persist) {
          try {
            await fs.rm(configFile);
          } catch {}
        }
        currentConfig = undefined;
      } else {
        await write(initial);
      }
    },
  } as StoreResult<T, TParams>;
};

const handleCorrupted = async (onCorrupted: StoreErrorDirective, name: string, configFile: string) => {
  switch (onCorrupted) {
    case 'error': {
      throw new Error(
        `Found corrupted store "${name}". The stored value doesn't match the current schema — this usually happens when the schema changes or the file is edited manually. Consider resetting or migrating the stored value.`,
      );
    }
    case 'warn': {
      // eslint-disable-next-line no-console
      console.warn(`Found corrupted store "${name}". The stored value doesn't match the current schema and will be ignored.`);
      break;
    }
    case 'delete': {
      await fs.rm(configFile);
      break;
    }
  }
};
